### ISSUE TITLE
Question: Can the "Hi" in this example be already rendered into HTML via SSR since it doesn't depend on an Event?

### ISSUE THREAD

**Issue by alaendle** [mikesol/deku-documentation#12]
While I played around with SSR I wondered if static text could be included in the rendered HTML - I used `text_`, but I think it's basically the same as in the example:

https://github.com/mikesol/deku-documentation/blob/6497175cad40dbdf44c6068f105a1ef6f961d3b7/src/Examples/RunSSR.purs#L13-L17

The reason I ask is that the content of elements affects the arrangement/location of the elements - so if static/constant text could be included in the HTML this would reduce changes during hydration.

**Comment by mikesol** [comment]
Hi! This is not quite possible yet, but what is possible is to use `pursx` in SSR. Does that correspond to your use case?

**Comment by alaendle** [comment]
Many thanks for the quick reply 👏; you are absolutely right - using `pursx` exposes the desired behavior.
