### ISSUE TITLE
Out of place example in Core/Collections/GroupsOfGroups

### ISSUE THREAD

**Issue by MonaMayrhofer** [mikesol/deku-documentation#18]
To me it seems that this paragraph has no connection to the associated example on the page.

https://github.com/mikesol/deku-documentation/blob/75330d4a2ec1fd3aad54e58651f45d7320fff536/src/Pages/CoreConcepts/Collections/FixedElements/GroupsOfGroups.purs#L33-L53

https://purescript-deku.netlify.app/core-concepts/collections#groups-of-groups

**Comment by MonaMayrhofer** [comment]
Reading further it actually seems that the paragraph was right, but the example was the wrong one.

The example in Core/Collections/GroupsOfGroups

https://github.com/mikesol/deku-documentation/blob/75330d4a2ec1fd3aad54e58651f45d7320fff536/src/Pages/CoreConcepts/Collections/FixedElements/GroupsOfGroups.purs#L15

is the same as in ComponentsAsMonoids

https://github.com/mikesol/deku-documentation/blob/75330d4a2ec1fd3aad54e58651f45d7320fff536/src/Pages/CoreConcepts/Collections/Monoids/ComponentsAsMonoids.purs#L17

**Comment by srghma** [comment]
true

![Screenshot](https://github.com/mikesol/deku-documentation/assets/7573215/f44ef38a-7ea0-405a-a8db-78f136dfd91a)

**Comment by mikesol** [comment]
Ooh nice catch, I've rewritten the text to correspond to the example (it's my favorite example in the docs 😝 )
