### ISSUE TITLE
Outdated mention of `Event` instead of `Poll`

### ISSUE THREAD

**Issue by prescientmoon** [mikesol/deku-documentation#19]
![Screenshot_20230913-130538_Chrome.jpg](https://github.com/mikesol/deku-documentation/assets/39400800/943357de-d67b-4c7a-9d1a-24b01b9b17ae)

In `Core concepts/collections`

**Comment by mikesol** [comment]
Thanks for flagging this!

**Comment by mikesol** [comment]
Fixed & thank you!
