### ISSUE TITLE
"Events aren't monoids" but they are

### ISSUE THREAD

**Issue by bakhtiyarneyman** [mikesol/deku-documentation#21]
Documentation:
https://purescript-deku.netlify.app/functional-reactive-programming/event-miscellany#events-aren't-monoids

Code: 
https://github.com/mikesol/purescript-hyrule/blob/aaff88c817803bcd583386ed91e0c9b835b7cc8c/src/FRP/Event.purs#L199

**Comment by srghma** [comment]
https://github.com/search?q=repo%3Amikesol%2Fpurescript-hyrule%20Monoid&type=code

not a Monoid anymore

but Poll is

**Comment by mikesol** [comment]
yessss sorry I'll fix!
