### ISSUE TITLE
Consider using typographically-correct symbols in the docs

### ISSUE THREAD

**Issue by toastal** [mikesol/deku-documentation#4]
This change would aid in readability and also just look nicer.

* `...` → `…` / `&hellip;`
* `'` → `‘` + `’` / `&lsquo` +  `&rsquo;`
* `"` → `“` + `”` / `&ldquo` +  `&rdquo;`

Given there is text in what looks like French possibly with accented characters, there is a precedence to not be limited to ANSI characters. Elements like `<q>` may also be appropriate.

(I’d push for `∷`, `→`, `∀`, but don’t wanna push my luck 😛)

**Comment by mikesol** [comment]
Good idea! Do you know of a tool that automatically does this sort of replacing? I'm fine with any replacements in the text, but these days I avoid unicode in PS files to make things more typeable and instead use VSCode to automatically visualize the prettier version without changing the underlying text.

**Comment by toastal** [comment]
Some tools like Pandoc can do “smart quotes”, but I don’t know any off the top of my head. It's a little trick since there can easily be false positives.

Continuing the aside: _typable_ is in the eye of the beholder. I recently saw someone open an issue in Djot because they normally use a Cyrillic key layout and typing the `x` in `[x]` was difficult. I had heard of an anecdote that PureScript toyed around with using `£` for piping after someone got frustrated with `$` being difficult with their layout.

**Comment by mikesol** [comment]
<img width="709" alt="Screenshot 2024-08-11 at 14 24 40" src="https://github.com/user-attachments/assets/732b00c7-6372-4d14-822a-8ee3d91eb72e">
<img width="54" alt="Screenshot 2024-08-11 at 14 24 20" src="https://github.com/user-attachments/assets/37b5d2a2-2ccb-4bda-9061-57e4fa446839">
Done!
