### ISSUE TITLE
Dark mode: headings in right hand nav are initially black

### ISSUE THREAD

**Issue by baffalop** [mikesol/deku-documentation#5]
Hi, I'm just reading through the documentation in dark mode and I noticed a styling issue.

The right hand "On this page" nav shows headings, with sub-items indented under them. In light mode, these are black, and light blue when viewing. In dark mode, I'm guessing they're supposed to be white and light blue when viewing; but instead they start off as black, but once they're highlighted in blue as viewed, _then_ they revert to white.

<img height="400" alt="image" src="https://user-images.githubusercontent.com/33629446/219905354-a1baddeb-d5f4-4cd6-affb-5612cd6da302.png"> <img height="400" alt="image" src="https://user-images.githubusercontent.com/33629446/219905465-f1829513-0c04-4c54-953f-7f21f9ba116e.png">

At first I thought that there were different styles for read vs. unread headings, and there was an oversight with the dark mode unread style, but I can't see a visible distinction in light mode so I'm guessing it's a subtler bug of some sort.

**Comment by baffalop** [comment]
I thought I'd use this as an opportunity to peek at some real-world Deku code, and looks like the crux of it is [here in App.purs](../blob/main/src/Components/App.purs#L77):

```purs
let
  rightSideNavClass' darktxt i =
    ( (rightSideNavSelect i $> true) <|>
        (rightSideNavDeselect i $> false)
    )
      <#>
        if _ then "text-sky-500"
        else "hover:text-slate-600 " <> darktxt <>
          " dark:hover:text-slate-300"
```

Indeed I can see that even in light mode, that hover style isn't applying to the "unread" headings, which confirms to me the hunch that until either select or deselect events emit, neither styles apply.

Could this be fixed by adding a final `pure false` to the alternative?

**Comment by mikesol** [comment]
I tried it & it worked, nice catch! I pushed a fix & also fixed an off-by-one error that happened when you clicked the right nav bar for the first time after navigating.
